### ISSUE TITLE
IDE not properly running program.

### ISSUE THREAD

**Issue by Curnal** [Taromaruu/Doggoscript#1]
Hello,
 I have showed plenty of interest in your programming language. I have built a program , saved, and attempted to run it via clicking "f5" and by hitting the "file > save > run ". After clicking run, nothing happens in the editor. Is there an update or method to fix this? 

Best regards, LanguageArtsGrade

**Comment by Taromaruu** [comment]
@Curnal Thanks for the issue!

Here is my guess on what the problem may be...

The doggoscript installer may not have added doggoscript to path right. Would you check your system path variables?

**Comment by Curnal** [comment]
@Taromaruu 
Hello, 

Yes. I have checked. During my installation, I selected all three choices. It did not request me to install in PATH. I just selected all and hit install. 

Stay safe, LanuageArtsGrade

**Comment by Taromaruu** [comment]
@Curnal Thanks for the reply.

I will try to fix this issue and reply back when there is a fix. Thanks for your request!

**Comment by Curnal** [comment]
@Taromaruu Hello, 

Thanks for the reply. 

Eyes, LanguageArtsGrade

**Comment by Taromaruu** [comment]
A integrated terminal will be added in the next update, this should solve the issue. I will close the issue for now.
